#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : GConf
Version  : 3.2.6
Release  : 10
URL      : https://download.gnome.org/sources/GConf/3.2/GConf-3.2.6.tar.xz
Source0  : https://download.gnome.org/sources/GConf/3.2/GConf-3.2.6.tar.xz
Summary  : GNOME Config System.
Group    : Development/Tools
License  : LGPL-2.0
Requires: GConf-bin = %{version}-%{release}
Requires: GConf-data = %{version}-%{release}
Requires: GConf-lib = %{version}-%{release}
Requires: GConf-libexec = %{version}-%{release}
Requires: GConf-license = %{version}-%{release}
Requires: GConf-locales = %{version}-%{release}
Requires: GConf-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : glibc-bin
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config
BuildRequires : pkgconfig(32dbus-1)
BuildRequires : pkgconfig(32dbus-glib-1)
BuildRequires : pkgconfig(32gio-2.0)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32gobject-2.0)
BuildRequires : pkgconfig(32gthread-2.0)
BuildRequires : pkgconfig(32gtk+-2.0)
BuildRequires : pkgconfig(32libxml-2.0)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libxml-2.0)

%description
GConf is a configuration database system, functionally similar to the
Windows registry but lots better. :-) It's being written for the GNOME
desktop but does not require GNOME; configure should notice if GNOME
is not installed and compile the basic GConf library anyway.

%package bin
Summary: bin components for the GConf package.
Group: Binaries
Requires: GConf-data = %{version}-%{release}
Requires: GConf-libexec = %{version}-%{release}
Requires: GConf-license = %{version}-%{release}
Requires: GConf-man = %{version}-%{release}

%description bin
bin components for the GConf package.


%package data
Summary: data components for the GConf package.
Group: Data

%description data
data components for the GConf package.


%package dev
Summary: dev components for the GConf package.
Group: Development
Requires: GConf-lib = %{version}-%{release}
Requires: GConf-bin = %{version}-%{release}
Requires: GConf-data = %{version}-%{release}
Provides: GConf-devel = %{version}-%{release}

%description dev
dev components for the GConf package.


%package dev32
Summary: dev32 components for the GConf package.
Group: Default
Requires: GConf-lib32 = %{version}-%{release}
Requires: GConf-bin = %{version}-%{release}
Requires: GConf-data = %{version}-%{release}
Requires: GConf-dev = %{version}-%{release}

%description dev32
dev32 components for the GConf package.


%package doc
Summary: doc components for the GConf package.
Group: Documentation
Requires: GConf-man = %{version}-%{release}

%description doc
doc components for the GConf package.


%package lib
Summary: lib components for the GConf package.
Group: Libraries
Requires: GConf-data = %{version}-%{release}
Requires: GConf-libexec = %{version}-%{release}
Requires: GConf-license = %{version}-%{release}

%description lib
lib components for the GConf package.


%package lib32
Summary: lib32 components for the GConf package.
Group: Default
Requires: GConf-data = %{version}-%{release}
Requires: GConf-license = %{version}-%{release}

%description lib32
lib32 components for the GConf package.


%package libexec
Summary: libexec components for the GConf package.
Group: Default

%description libexec
libexec components for the GConf package.


%package license
Summary: license components for the GConf package.
Group: Default

%description license
license components for the GConf package.


%package locales
Summary: locales components for the GConf package.
Group: Default

%description locales
locales components for the GConf package.


%package man
Summary: man components for the GConf package.
Group: Default

%description man
man components for the GConf package.


%prep
%setup -q -n GConf-3.2.6
pushd ..
cp -a GConf-3.2.6 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539026149
%configure --disable-static --disable-orbit --sysconfdir=/usr/share/defaults/etc
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="$ASFLAGS --32"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static --disable-orbit --sysconfdir=/usr/share/defaults/etc   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1539026149
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/GConf
cp COPYING %{buildroot}/usr/share/package-licenses/GConf/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang GConf2

%files
%defattr(-,root,root,-)
/usr/lib32/girepository-1.0/GConf-2.0.typelib

%files bin
%defattr(-,root,root,-)
/usr/bin/gconf-merge-tree
/usr/bin/gconftool-2
/usr/bin/gsettings-data-convert
/usr/bin/gsettings-schema-convert

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GConf-2.0.typelib
/usr/share/dbus-1/services/org.gnome.GConf.service
/usr/share/defaults/etc/gconf/2/path
/usr/share/defaults/etc/xdg/autostart/gsettings-data-convert.desktop
/usr/share/gir-1.0/*.gir
/usr/share/sgml/gconf/gconf-1.0.dtd

%files dev
%defattr(-,root,root,-)
/usr/include/gconf/2/gconf/gconf-changeset.h
/usr/include/gconf/2/gconf/gconf-client.h
/usr/include/gconf/2/gconf/gconf-engine.h
/usr/include/gconf/2/gconf/gconf-enum-types.h
/usr/include/gconf/2/gconf/gconf-error.h
/usr/include/gconf/2/gconf/gconf-listeners.h
/usr/include/gconf/2/gconf/gconf-schema.h
/usr/include/gconf/2/gconf/gconf-value.h
/usr/include/gconf/2/gconf/gconf.h
/usr/lib64/libgconf-2.so
/usr/lib64/pkgconfig/gconf-2.0.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libgconf-2.so
/usr/lib32/pkgconfig/32gconf-2.0.pc
/usr/lib32/pkgconfig/gconf-2.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gconf/ch01.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-backend.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-changeset.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-client.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-engine.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-error.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-internals.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-listeners.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-locale.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-schema.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-sources.html
/usr/share/gtk-doc/html/gconf/gconf-gconf-value.html
/usr/share/gtk-doc/html/gconf/gconf-gconf.html
/usr/share/gtk-doc/html/gconf/gconf.devhelp2
/usr/share/gtk-doc/html/gconf/home.png
/usr/share/gtk-doc/html/gconf/index.html
/usr/share/gtk-doc/html/gconf/index.sgml
/usr/share/gtk-doc/html/gconf/left.png
/usr/share/gtk-doc/html/gconf/right.png
/usr/share/gtk-doc/html/gconf/style.css
/usr/share/gtk-doc/html/gconf/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/GConf/2/libgconfbackend-oldxml.so
/usr/lib64/GConf/2/libgconfbackend-xml.so
/usr/lib64/gio/modules/libgsettingsgconfbackend.so
/usr/lib64/libgconf-2.so.4
/usr/lib64/libgconf-2.so.4.1.5

%files lib32
%defattr(-,root,root,-)
/usr/lib32/GConf/2/libgconfbackend-oldxml.so
/usr/lib32/GConf/2/libgconfbackend-xml.so
/usr/lib32/gio/modules/libgsettingsgconfbackend.so
/usr/lib32/libgconf-2.so.4
/usr/lib32/libgconf-2.so.4.1.5

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gconfd-2

%files license
%defattr(-,root,root,-)
/usr/share/package-licenses/GConf/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/gconftool-2.1
/usr/share/man/man1/gsettings-data-convert.1
/usr/share/man/man1/gsettings-schema-convert.1

%files locales -f GConf2.lang
%defattr(-,root,root,-)

